#!/bin/sh

echo "PWD: $PWD"

set -a
source "$PWD/.env"
set +a

# PULL_REQUEST_TEMPLATE=$(cat ./.github/PULL_REQUEST_TEMPLATE.md)
PULL_REQUEST_TEMPLATE="This is a pull request template."
# Get username git config
OWNER=$(git config user.name)
# Get repository name
REPO=$(basename -s .git `git config --get remote.origin.url`)
echo "Pull request template: $PULL_REQUEST_TEMPLATE"

# Get the current branch name
branch=$(git rev-parse --abbrev-ref HEAD)

# Check if a pull request already exists for the current branch
pull_request_exists=$(curl -s -H "Authorization: token $TOKEN" https://api.github.com/repos/OWNER/REPO/pulls?head=OWNER:$branch | jq '.[].head.ref' | grep $branch)

LINK="https://api.github.com/repos/$OWNER/$REPO/pulls"
BODY_REQUEST={"title":"New pull request from '$branch'","body":"'$PULL_REQUEST_TEMPLATE'","head":"'$branch'","base":"main"}
echo "Body request: $BODY_REQUEST"

# If the pull request does not exist, create a new one
if [ -z "$pull_request_exists" ]; then
    # curl -H "Authorization: token $TOKEN" -X POST -d '{"title": "New pull request from '$branch'","head": "'$branch'","base": "main", "body": "'$PULL_REQUEST_TEMPLATE'"}' https://api.github.com/repos/OWNER/REPO/pulls
    curl \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  $LINK \
  -d "'$BODY_REQUEST'"
fi
