version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    # Check for updates once a week
    schedule:
      # interval: "daily"
      # cron a cada 5 minutos
      cron: "*/5 * * * *"
