repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.3
    hooks:
      - id: autopep8
        # args: [--in-place, --aggressive, --aggressive]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v1.18.2
    hooks:
      - id: prettier
        args: [--write]
