name: Python Package using pip

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Pip install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Lint with Pylint
        run: |
          # pylint disables:
          #   W0703: Catching too general exception Exception
          #   E0401: Unable to import 'module'
          #   C0114: Missing module docstring
          pylint . --recursive=y --output-format=colorized --reports=n --score=n --disable=W0703,E0401,C0114,E0401

      - name: Lint with Black
        run: |
          black --check --diff --color .

  testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Pip install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test with unittest
        run: |
          python -m unittest discover -s ./src -p "*_test.py"
